### PR TITLE
fix(frontend): org image upload modal shows empty file list after upload

### LINKED ISSUE #2117: Bug: Organization image upload modal shows empty file list after upload
### Terms

- [x] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [x] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Behavior

After uploading an image through the organization image carousel modal on the About page, reopening the modal shows an empty file list ("Number of files: 0"). The upload itself succeeds — the carousel updates to show the new image — but the modal has no memory of it and shows nothing when opened again.

This is distinct from the delete-side bug fixed in #2109. Deletion still works correctly.

**Steps to reproduce**

1. Navigate to an organization's About page as an admin.
2. Click the edit icon on the image carousel to open the upload modal.
3. Upload one or more images and click Upload.
4. Wait for the modal to close.
5. Click the edit icon again to reopen the modal.

**Expected behavior**

The modal shows the newly uploaded images in the file list.

**Actual behavior**

The modal shows "Number of files: 0". The uploaded images are missing.

### PR DESCRIPTION
**Pull request by aasimsyed**
### Contributor checklist

- [x] This pull request is on a separate branch and not the main branch
- [x] I have run the tests for the backend and frontend depending on what's needed for my changes as described in the testing section of the contributing guide

---

### Description

Fixes the org image upload modal showing "Number of files: 0" after an upload. The upload itself succeeds and the carousel updates, but reopening the modal shows nothing. Related to #1791, the delete path was fixed in #2109 but this upload path was not fixed.

Found three issues while tracing through the E2E tests in #1665:

- **`OrganizationPage.vue`** — the layout was passing `organization?.id` to the modal as `orgId`, but that value is `null` on first render before the org data loads. This meant the modal's data fetcher registered under the wrong cache key, so the post-upload cache refresh never reached it. Fixed by passing the route param instead, which is always correct.

- **`ImageMultipleFileDropZone.vue`** — `watch(props.modelValue)` was missing a getter function, so Vue never detected when the parent replaced the file array. Changed to `watch(() => props.modelValue)`.

- **`ModalUploadImageOrganization.vue`** — the watch that populates the file list was appending new results on top of existing ones instead of replacing them, causing duplicates to accumulate across refreshes.

Tested manually and via the E2E tests in #1665.

### Related issue

- Closes #2117

### CODE REVIEW

**Comment by nicki182** [comment]
@aasimsyed did you check if this is happening in groups too?

**Comment by aasimsyed** [comment]
@nicki182 thanks for pointing that out. I forgot and yes, same behavior with the same issues was present in the group upload modal. Added a fix that applies the identical groupId route param fix to `GroupPage.vue` and the same `pendingUploads` concat fix to ModalUploadImageGroup.vue.

**Comment by nicki182** [comment]
@aasimsyed Ok, I'll take on it possibly today and bring it in most likely

**Comment by nicki182** [comment]
@aasimsyed there is a test from faq that is failing can you confirm if it's a flaky test or an actual bug that we need to look into?

**Comment by aasimsyed** [comment]
@nicki182 test passes fine locally across many runs and nothing related to taht test was touched. It's just flaky.

**Comment by nicki182** [comment]
@aasimsyed ok, so all good

**Comment by aasimsyed** [comment]
@nicki182 I added a refactor to fix the flaky test. E2E now passes

File: frontend/app/layouts/organization/OrganizationPage.vue [hunk 1]
```diff
@@ -4,11 +4,11 @@
     <ModalUploadImageOrganization
       @closeModal="handleCloseModalUploadImage"
       :images="images || []"
-      :orgId="organization?.id || ''"
+      :orgId="orgId || ''"
     />
     <ModalUploadImageIcon
       @closeModal="handleCloseModalUploadImageIcon"
-      :entityId="organization?.id || ''"
+      :entityId="orgId || ''"
```
Comment (andrewtavis) [inline frontend/app/layouts/organization/OrganizationPage.vue:11]: Figured we can do the same as the above here, @aasimsyed :)

**Review by andrewtavis — APPROVED** [review]
praise: All's looking and working great, @aasimsyed! Thanks for picking this one up and finalizing it so quickly!
